
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import ThemeProvider from '@/theme'
import ThemeLocalization from '@/theme/ThemeLocalization'
import { SnackbarProvider } from 'notistack';
import Layout from '@/components/Layout'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
})
 {
 
  return (
    <html lang="en">
      <body className={inter.className} style={{padding:"40px",background:"#f0f3fb"}}>
      <Layout >
      
      <ThemeProvider>
      <ThemeLocalization>
        {children}
        </ThemeLocalization>
    </ThemeProvider> 
   
      </Layout>
   
    
      
  
      
        </body>
    </html>
  )
}
